INSERT INTO guide (id_char, role_char, id_soul, soul_2, soul_4, soul_6) VALUES
(41 , 'DMG Amplifier',22, 'SPD', 'Effect HIT', 'HP%'),
(95 ,  'DMG Amplifier',23, 'HP%', 'HP%', 'HP%'),
(43 ,  'DMG Amplifier',30, 'SPD', 'Effect HIT', 'HP%'),
(135 ,'DMG Amplifier', 23, 'HP%', 'HP%', 'Crit'),
(107 , 'DPS', 19, 'ATK%', 'ATK%', 'Crit'),
(11 ,  'DPS', 19, 'ATK%', 'ATK%', 'Crit'),
(121 , 'DPS', 19, 'ATK%', 'ATK%', 'Crit'),
(144 , 'DPS', 19, 'ATK%', 'ATK%', 'Crit'),
(26 ,  'DPS', 19, 'ATK%', 'ATK%', 'Crit DMG'),
(6 ,  'DPS', 16, 'ATK%', 'ATK%', 'Crit'),
(132 , 'DPS', 16, 'ATK%', 'ATK%', 'Crit'),
(115 , 'DPS', 16, 'ATK%', 'ATK%', 'Crit'),
(46,  'Orb provider', 7, NULL, NULL, NULL),
(101 , 'Orb provider', 23, 'SPD', 'HP%', 'HP%'),
(85 , 'Orb provider', 6, 'HP%', 'HP%', 'HP%'),
(59 ,  'Puller', 23, 'SPD', 'HP%', 'HP%'),
(19 ,  'Puller', 23, 'SPD', 'HP%', 'HP%'),
(17 , 'Healer', 20, 'HP%', 'HP%', 'Crit'),
(109 , 'Healer', 13, 'HP%', 'HP%', 'Crit'),
(62, 'Healer', 13, 'ATK%', 'ATK%', 'Crit');