INSERT INTO soul (id, soul_type, combo_1) VALUES
(1, 'normal', NULL),
(2, 'normal', NULL),
(3,  'normal', NULL),
(4, 'normal', NULL),
(5,'normal', NULL),
(6, 'normal', NULL),
(7, 'normal', NULL),
(8, 'normal', NULL),
(9, 'normal', NULL),
(10,'normal', NULL),
(11, 'normal', NULL),
(12, 'normal', NULL),
(13, 'normal', NULL),
(14, 'normal', NULL),
(15,'normal', NULL),
(16,'normal', NULL),
(17, 'normal', NULL),
(18,'normal', NULL),
(19, 'normal', NULL),
(20, 'normal', NULL),
(21, 'normal', NULL),
(22,'normal', NULL),
(23, 'normal', NULL),
(24, 'normal', NULL),
(25, 'normal', NULL),
(26,'normal', NULL),
(27,'normal', NULL),
(28,'normal', NULL),
(29, 'normal', NULL),
(30, 'normal', NULL),
(31,'normal', NULL),
(32, 'normal', NULL),
(33, 'normal', NULL),
(34, 'boss', 'Random Stat 8% (DEF bonus 16%, except SPD and Crit DMG)'),
(35, 'boss', 'Random Stat 8% (DEF bonus 16%, except SPD and Crit DMG)'),
(36, 'boss', 'Random Stat 8% (DEF bonus 16%, except SPD and Crit DMG)'),
(37,'boss', 'Random Stat 8% (DEF bonus 16%, except SPD and Crit DMG)'),
(38, 'boss', 'Random Stat 8% (DEF bonus 16%, except SPD and Crit DMG)'),
(39, 'normal', NULL),
(40,'normal', NULL),
(41, 'normal', NULL),
(42, 'normal', NULL),
(43,'boss', 'Random Stat 8% (DEF bonus 16%, except SPD and Crit DMG)')
ON DUPLICATE KEY UPDATE 
soul_type = VALUES(soul_type),
combo_1 = VALUES(combo_1);